QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Autonomo', payment = 10 } } },
	bus = { label = 'Onibus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Motorista', payment = 50 } } },
	judge = { label = 'Judiciario', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juiz', payment = 100 } } },
	lawyer = { label = 'Escritorio de Advocacia', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associado', payment = 50 } } },
	reporter = { label = 'Imprensa', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Jornalista', payment = 50 } } },
	trucker = { label = 'Caminhoneiro', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Motorista', payment = 50 } } },
	tow = { label = 'Guincho', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Motorista', payment = 50 } } },
	garbage = { label = 'Coleta de Lixo', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Coletor', payment = 50 } } },
	vineyard = { label = 'Vinhedo', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Colhedor', payment = 50 } } },
	hotdog = { label = 'Hot-dog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vendedor', payment = 50 } } },

	police = {
		label = 'Policia',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Oficial', payment = 75 },
			['2'] = { name = 'Sargento', payment = 100 },
			['3'] = { name = 'Tenente', payment = 125 },
			['4'] = { name = 'Comandante', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'Atendimento Medico',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Paramedico', payment = 75 },
			['2'] = { name = 'Medico', payment = 100 },
			['3'] = { name = 'Cirurgiao', payment = 125 },
			['4'] = { name = 'Diretor', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Imobiliaria',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Venda de Casas', payment = 75 },
			['2'] = { name = 'Venda Comercial', payment = 100 },
			['3'] = { name = 'Corretor', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Motorista', payment = 75 },
			['2'] = { name = 'Motorista de Evento', payment = 100 },
			['3'] = { name = 'Vendas', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Concessionaria',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Vendedor de Loja', payment = 75 },
			['2'] = { name = 'Venda Comercial', payment = 100 },
			['3'] = { name = 'Financeiro', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Novato', payment = 75 },
			['2'] = { name = 'Experiente', payment = 100 },
			['3'] = { name = 'Avancado', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Novato', payment = 75 },
			['2'] = { name = 'Experiente', payment = 100 },
			['3'] = { name = 'Avancado', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Novato', payment = 75 },
			['2'] = { name = 'Experiente', payment = 100 },
			['3'] = { name = 'Avancado', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Novato', payment = 75 },
			['2'] = { name = 'Experiente', payment = 100 },
			['3'] = { name = 'Avancado', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruta', payment = 50 },
			['1'] = { name = 'Novato', payment = 75 },
			['2'] = { name = 'Experiente', payment = 100 },
			['3'] = { name = 'Avancado', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
}
