QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`]               = { name = 'weapon_unarmed', label = 'Punhos', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_dagger`]                = { name = 'weapon_dagger', label = 'Adaga', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_bat`]                   = { name = 'weapon_bat', label = 'Taco de beisebol', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_bottle`]                = { name = 'weapon_bottle', label = 'Garrafa quebrada', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_crowbar`]               = { name = 'weapon_crowbar', label = 'Pe de cabra', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_flashlight`]            = { name = 'weapon_flashlight', label = 'Lanterna', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_golfclub`]              = { name = 'weapon_golfclub', label = 'Taco de golfe', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_hammer`]                = { name = 'weapon_hammer', label = 'Martelo', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_hatchet`]               = { name = 'weapon_hatchet', label = 'Machadinha', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_knuckle`]               = { name = 'weapon_knuckle', label = 'Soco ingles', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_knife`]                 = { name = 'weapon_knife', label = 'Faca', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_machete`]               = { name = 'weapon_machete', label = 'Facao', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_switchblade`]           = { name = 'weapon_switchblade', label = 'Canivete', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_nightstick`]            = { name = 'weapon_nightstick', label = 'Cassetete', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_wrench`]                = { name = 'weapon_wrench', label = 'Chave inglesa', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_battleaxe`]             = { name = 'weapon_battleaxe', label = 'Machado de batalha', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_poolcue`]               = { name = 'weapon_poolcue', label = 'Taco de sinuca', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_briefcase`]             = { name = 'weapon_briefcase', label = 'Maleta', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_briefcase_02`]          = { name = 'weapon_briefcase_02', label = 'Maleta', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_garbagebag`]            = { name = 'weapon_garbagebag', label = 'Saco de lixo', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_handcuffs`]             = { name = 'weapon_handcuffs', label = 'Algemas', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_bread`]                 = { name = 'weapon_bread', label = 'Baguete', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered' },
	[`weapon_stone_hatchet`]         = { name = 'weapon_stone_hatchet', label = 'Machadinha de pedra', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Knifed / Stabbed / Eviscerated' },
	[`weapon_candycane`]             = { name = 'weapon_candycane', label = 'Bengala doce', weapontype = 'Corpo a corpo', ammotype = nil, damagereason = 'Melee Killed / Whacked / Executed / Beat down / Musrdered / Battered / Candy Caned' },

	-- Handguns
	[`weapon_pistol`]                = { name = 'weapon_pistol', label = 'Pistola', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_pistol_mk2`]            = { name = 'weapon_pistol_mk2', label = 'Pistola Mk2', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_combatpistol`]          = { name = 'weapon_combatpistol', label = 'Pistola de combate', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_appistol`]              = { name = 'weapon_appistol', label = 'Pistola AP', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_stungun`]               = { name = 'weapon_stungun', label = 'Taser', weapontype = 'Pistola', ammotype = 'AMMO_STUNGUN', damagereason = 'Died' },
	[`weapon_pistol50`]              = { name = 'weapon_pistol50', label = 'Pistola .50 Cal', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_snspistol`]             = { name = 'weapon_snspistol', label = 'Pistola SNS', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_snspistol_mk2`]         = { name = 'weapon_snspistol_mk2', label = 'Pistola SNS MK2', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_heavypistol`]           = { name = 'weapon_heavypistol', label = 'Pistola pesada', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_vintagepistol`]         = { name = 'weapon_vintagepistol', label = 'Pistola vintage', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_flaregun`]              = { name = 'weapon_flaregun', label = 'Sinalizador', weapontype = 'Pistola', ammotype = 'AMMO_FLARE', damagereason = 'Died' },
	[`weapon_marksmanpistol`]        = { name = 'weapon_marksmanpistol', label = 'Pistola de atirador', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_revolver`]              = { name = 'weapon_revolver', label = 'Revolver', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_revolver_mk2`]          = { name = 'weapon_revolver_mk2', label = 'Revolver MK2', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_doubleaction`]          = { name = 'weapon_doubleaction', label = 'Revolver de acao dupla', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_raypistol`]             = { name = 'weapon_raypistol', label = 'Pistola de raios', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_ceramicpistol`]         = { name = 'weapon_ceramicpistol', label = 'Pistola de ceramica', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_navyrevolver`]          = { name = 'weapon_navyrevolver', label = 'Revolver naval', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_gadgetpistol`]          = { name = 'weapon_gadgetpistol', label = 'Pistola gadget', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plugged / Bust a cap in' },
	[`weapon_stungun_mp`]            = { name = 'weapon_stungun_mp', label = 'Taser', weapontype = 'Pistola', ammotype = 'AMMO_STUNGUN', damagereason = 'Died' },
	[`weapon_pistolxm3`]             = { name = 'weapon_pistolxm3', label = 'Pistola XM3', weapontype = 'Pistola', ammotype = 'AMMO_PISTOL', damagereason = 'Pistoled / Blasted / Plaugged / Bust a cap in' },

	-- Submachine Guns
	[`weapon_microsmg`]              = { name = 'weapon_microsmg', label = 'Micro SMG', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_smg`]                   = { name = 'weapon_smg', label = 'SMG', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_smg_mk2`]               = { name = 'weapon_smg_mk2', label = 'SMG MK2', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_assaultsmg`]            = { name = 'weapon_assaultsmg', label = 'SMG de assalto', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_combatpdw`]             = { name = 'weapon_combatpdw', label = 'PDW de combate', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_machinepistol`]         = { name = 'weapon_machinepistol', label = 'Tec-9', weapontype = 'Submetralhadora', ammotype = 'AMMO_PISTOL', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_minismg`]               = { name = 'weapon_minismg', label = 'Mini SMG', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },
	[`weapon_raycarbine`]            = { name = 'weapon_raycarbine', label = 'Carabina de raios', weapontype = 'Submetralhadora', ammotype = 'AMMO_SMG', damagereason = 'Riddled / Drilled / Finished / Submachine Gunned' },

	-- Shotguns
	[`weapon_pumpshotgun`]           = { name = 'weapon_pumpshotgun', label = 'Escopeta pump', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_pumpshotgun_mk2`]       = { name = 'weapon_pumpshotgun_mk2', label = 'Escopeta pump MK2', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_sawnoffshotgun`]        = { name = 'weapon_sawnoffshotgun', label = 'Escopeta serrada', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_assaultshotgun`]        = { name = 'weapon_assaultshotgun', label = 'Escopeta de assalto', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_bullpupshotgun`]        = { name = 'weapon_bullpupshotgun', label = 'Escopeta bullpup', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_musket`]                = { name = 'weapon_musket', label = 'Mosquete', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_heavyshotgun`]          = { name = 'weapon_heavyshotgun', label = 'Escopeta pesada', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_dbshotgun`]             = { name = 'weapon_dbshotgun', label = 'Escopeta de dois canos', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_autoshotgun`]           = { name = 'weapon_autoshotgun', label = 'Escopeta automatica', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },
	[`weapon_combatshotgun`]         = { name = 'weapon_combatshotgun', label = 'Escopeta de combate', weapontype = 'Escopeta', ammotype = 'AMMO_SHOTGUN', damagereason = 'Devastated / Pulverized / Shotgunned' },

	-- Assault Rifles
	[`weapon_assaultrifle`]          = { name = 'weapon_assaultrifle', label = 'Rifle de assalto', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_assaultrifle_mk2`]      = { name = 'weapon_assaultrifle_mk2', label = 'Rifle de assalto MK2', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_carbinerifle`]          = { name = 'weapon_carbinerifle', label = 'Rifle carabina', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_carbinerifle_mk2`]      = { name = 'weapon_carbinerifle_mk2', label = 'Rifle carabina MK2', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_advancedrifle`]         = { name = 'weapon_advancedrifle', label = 'Rifle avancado', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_specialcarbine`]        = { name = 'weapon_specialcarbine', label = 'Carabina especial', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_specialcarbine_mk2`]    = { name = 'weapon_specialcarbine_mk2', label = 'Carabina especial MK2', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_bullpuprifle`]          = { name = 'weapon_bullpuprifle', label = 'Rifle bullpup', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_bullpuprifle_mk2`]      = { name = 'weapon_bullpuprifle_mk2', label = 'Rifle bullpup MK2', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_compactrifle`]          = { name = 'weapon_compactrifle', label = 'Rifle compacto', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_militaryrifle`]         = { name = 'weapon_militaryrifle', label = 'Rifle militar', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },
	[`weapon_heavyrifle`]            = { name = 'weapon_heavyrifle', label = 'Rifle pesado', weapontype = 'Rifle de assalto', ammotype = 'AMMO_RIFLE', damagereason = 'Ended / Rifled / Shot down / Floored' },

	-- Light Machine Guns
	[`weapon_mg`]                    = { name = 'weapon_mg', label = 'Metralhadora', weapontype = 'Metralhadora leve', ammotype = 'AMMO_MG', damagereason = 'Machine gunned / Sprayed / Ruined' },
	[`weapon_combatmg`]              = { name = 'weapon_combatmg', label = 'Metralhadora de combate', weapontype = 'Metralhadora leve', ammotype = 'AMMO_MG', damagereason = 'Machine gunned / Sprayed / Ruined' },
	[`weapon_combatmg_mk2`]          = { name = 'weapon_combatmg_mk2', label = 'Metralhadora de combate MK2', weapontype = 'Metralhadora leve', ammotype = 'AMMO_MG', damagereason = 'Machine gunned / Sprayed / Ruined' },
	[`weapon_gusenberg`]             = { name = 'weapon_gusenberg', label = 'SMG Thompson', weapontype = 'Metralhadora leve', ammotype = 'AMMO_MG', damagereason = 'Machine gunned / Sprayed / Ruined' },

	-- Sniper Rifles
	[`weapon_sniperrifle`]           = { name = 'weapon_sniperrifle', label = 'Rifle sniper', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER', damagereason = 'Sniped / Picked off / Scoped' },
	[`weapon_heavysniper`]           = { name = 'weapon_heavysniper', label = 'Sniper pesado', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER', damagereason = 'Sniped / Picked off / Scoped' },
	[`weapon_heavysniper_mk2`]       = { name = 'weapon_heavysniper_mk2', label = 'Sniper pesado MK2', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER', damagereason = 'Sniped / Picked off / Scoped' },
	[`weapon_marksmanrifle`]         = { name = 'weapon_marksmanrifle', label = 'Rifle de atirador', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER', damagereason = 'Sniped / Picked off / Scoped' },
	[`weapon_marksmanrifle_mk2`]     = { name = 'weapon_marksmanrifle_mk2', label = 'Rifle de atirador MK2', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER', damagereason = 'Sniped / Picked off / Scoped' },
	[`weapon_remotesniper`]          = { name = 'weapon_remotesniper', label = 'Sniper remoto', weapontype = 'Rifle sniper', ammotype = 'AMMO_SNIPER_REMOTE', damagereason = 'Sniped / Picked off / Scoped' },

	-- Heavy Weapons
	[`weapon_rpg`]                   = { name = 'weapon_rpg', label = 'RPG', weapontype = 'Armas pesadas', ammotype = 'AMMO_RPG', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_grenadelauncher`]       = { name = 'weapon_grenadelauncher', label = 'Lancador de granadas', weapontype = 'Armas pesadas', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_grenadelauncher_smoke`] = { name = 'weapon_grenadelauncher_smoke', label = 'Lancador de granada de fumaca', weapontype = 'Armas pesadas', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_minigun`]               = { name = 'weapon_minigun', label = 'Minigun', weapontype = 'Armas pesadas', ammotype = 'AMMO_MINIGUN', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_firework`]              = { name = 'weapon_firework', label = 'Lancador de fogos', weapontype = 'Armas pesadas', ammotype = nil, damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_railgun`]               = { name = 'weapon_railgun', label = 'Railgun', weapontype = 'Armas pesadas', ammotype = nil, damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_railgunxm3`]            = { name = 'weapon_railgunxm3', label = 'Railgun XM3', weapontype = 'Armas pesadas', ammotype = nil, damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_hominglauncher`]        = { name = 'weapon_hominglauncher', label = 'Lancador teleguiado', weapontype = 'Armas pesadas', ammotype = 'AMMO_STINGER', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_compactlauncher`]       = { name = 'weapon_compactlauncher', label = 'Lancador compacto', weapontype = 'Armas pesadas', ammotype = nil, damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_rayminigun`]            = { name = 'weapon_rayminigun', label = 'Minigun de raios', weapontype = 'Armas pesadas', ammotype = 'AMMO_MINIGUN', damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_emplauncher`]           = { name = 'weapon_emplauncher', label = 'Lancador EMP', weapontype = 'Armas pesadas', ammotype = 'AMMO_EMPLAUNCHER', damagereason = 'Died' },

	-- Throwables
	[`weapon_grenade`]               = { name = 'weapon_grenade', label = 'Granada', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Bombed / Exploded / Detonated / Blew up' },
	[`weapon_bzgas`]                 = { name = 'weapon_bzgas', label = 'Gas BZ', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Died' },
	[`weapon_molotov`]               = { name = 'weapon_molotov', label = 'Molotov', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Torched / Flambeed / Barbecued' },
	[`weapon_stickybomb`]            = { name = 'weapon_stickybomb', label = 'C4', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Bombed / Exploded / Detonated / Blew up' },
	[`weapon_proxmine`]              = { name = 'weapon_proxmine', label = 'Mina de proximidade', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Bombed / Exploded / Detonated / Blew up' },
	[`weapon_snowball`]              = { name = 'weapon_snowball', label = 'Bola de neve', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Died' },
	[`weapon_pipebomb`]              = { name = 'weapon_pipebomb', label = 'Bomba caseira', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Bombed / Exploded / Detonated / Blew up' },
	[`weapon_ball`]                  = { name = 'weapon_ball', label = 'Bola', weapontype = 'Arremessavel', ammotype = 'AMMO_BALL', damagereason = 'Died' },
	[`weapon_smokegrenade`]          = { name = 'weapon_smokegrenade', label = 'Granada de fumaca', weapontype = 'Arremessavel', ammotype = nil, damagereason = 'Died' },
	[`weapon_flare`]                 = { name = 'weapon_flare', label = 'Sinalizador', weapontype = 'Arremessavel', ammotype = 'AMMO_FLARE', damagereason = 'Died' },

	-- Miscellaneous
	[`weapon_petrolcan`]             = { name = 'weapon_petrolcan', label = 'Galao de gasolina', weapontype = 'Diversos', ammotype = 'AMMO_PETROLCAN', damagereason = 'Died' },
	[`gadget_parachute`]             = { name = 'gadget_parachute', label = 'Paraquedas', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_fireextinguisher`]      = { name = 'weapon_fireextinguisher', label = 'Extintor de incendio', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_hazardcan`]             = { name = 'weapon_hazardcan', label = 'Galao perigoso', weapontype = 'Diversos', ammotype = 'AMMO_PETROLCAN', damagereason = 'Died' },
	[`weapon_fertilizercan`]         = { name = 'weapon_fertilizercan', label = 'Galao de fertilizante', weapontype = 'Diversos', ammotype = 'AMMO_FERTILIZERCAN', damagereason = 'Died' },
	[`weapon_barbed_wire`]           = { name = 'weapon_barbed_wire', label = 'Arame farpado', weapontype = 'Diversos', ammotype = nil, damagereason = 'Prodded' },
	[`weapon_drowning`]              = { name = 'weapon_drowning', label = 'Afogamento', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_drowning_in_vehicle`]   = { name = 'weapon_drowning_in_vehicle', label = 'Afogamento em veiculo', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_bleeding`]              = { name = 'weapon_bleeding', label = 'Sangramento', weapontype = 'Diversos', ammotype = nil, damagereason = 'Bled out' },
	[`weapon_electric_fence`]        = { name = 'weapon_electric_fence', label = 'Cerca eletrica', weapontype = 'Diversos', ammotype = nil, damagereason = 'Fried' },
	[`weapon_explosion`]             = { name = 'weapon_explosion', label = 'Explosao', weapontype = 'Diversos', ammotype = nil, damagereason = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated' },
	[`weapon_fall`]                  = { name = 'weapon_fall', label = 'Queda', weapontype = 'Diversos', ammotype = nil, damagereason = 'Committed suicide' },
	[`weapon_exhaustion`]            = { name = 'weapon_exhaustion', label = 'Exaustao', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_hit_by_water_cannon`]   = { name = 'weapon_hit_by_water_cannon', label = 'Canhao de agua', weapontype = 'Diversos', ammotype = nil, damagereason = 'Died' },
	[`weapon_rammed_by_car`]         = { name = 'weapon_rammed_by_car', label = 'Atropelado por veiculo', weapontype = 'Diversos', ammotype = nil, damagereason = 'Flattened / Ran over / Ran down' },
	[`weapon_run_over_by_car`]       = { name = 'weapon_run_over_by_car', label = 'Passou por cima - veiculo', weapontype = 'Diversos', ammotype = nil, damagereason = 'Flattened / Ran over / Ran down' },
	[`weapon_heli_crash`]            = { name = 'weapon_heli_crash', label = 'Queda de helicoptero', weapontype = 'Diversos', ammotype = nil, damagereason = 'Helicopter Crash' },
	[`weapon_fire`]                  = { name = 'weapon_fire', label = 'Fogo', weapontype = 'Diversos', ammotype = nil, damagereason = 'Torched / Flambeed / Barbecued' },

	-- Animals
	[`weapon_animal`]                = { name = 'weapon_animal', label = 'Animal', weapontype = 'Animais', ammotype = nil, damagereason = 'Mauled' },
	[`weapon_cougar`]                = { name = 'weapon_cougar', label = 'Puma', weapontype = 'Animais', ammotype = nil, damagereason = 'Mauled' },
}
