Config = Config or {}

Config.NotifyAllocate = true
Config.RespecTax = 0.15
Config.MaxRefundTaxPoints = 25

Config.Inventory = {
    resource = 'qb-inventory',
}

Config.RespecItem = {
    enabled = true,
    item = 'skill_reset_token',
    label = 'Token de Reset de Habilidades',
    description = 'Remove nos alocados da arvore de habilidades e devolve pontos com taxa.',
    image = 'certificate.png',
    weight = 0,
    amount = 1,
}

Config.Commands = {
    open = 'skilltree',
    adminReset = 'resetskilltree',
}

Config.Trees = {
    neutral = {
        label = 'Sobrevivencia',
        description = 'Passivas universais para exploracao, fadiga e recuperacao em Distopia.',
        category = 'Neutra',
        nodes = {
            grit = {
                label = 'Pulso firme',
                description = 'Melhora a resistencia geral em situacoes de risco.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { mitigation = 0.01, staminaDrain = -0.02 },
                x = 10,
                y = 46,
            },
            field_senses = {
                label = 'Sentidos de campo',
                description = 'Facilita leitura de trilhas, rotas e ameacas proximas.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 1, 2 },
                requires = { 'grit:rank1' },
                effects = { tracking = 0.03 },
                x = 34,
                y = 26,
            },
            improvised_care = {
                label = 'Cuidado improvisado',
                description = 'Aumenta eficiencia de recuperacao e suporte basico.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 1, 2 },
                requires = { 'grit:rank1' },
                effects = { healing = 0.03 },
                x = 34,
                y = 66,
            },
            weathered_lungs = {
                label = 'Pulmoes calejados',
                description = 'Reduz desgaste causado por corridas longas e frio moderado.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 2, 2 },
                requires = { 'field_senses:rank1' },
                effects = { staminaDrain = -0.015, mitigation = 0.005 },
                x = 56,
                y = 18,
            },
            scavenger_habit = {
                label = 'Habito de saque',
                description = 'Aprimora aproveitamento de recursos e reparos simples.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'field_senses:rank1' },
                effects = { crafting = 0.025 },
                x = 58,
                y = 34,
            },
            blood_calm = {
                label = 'Sangue frio',
                description = 'Ajuda a manter controle quando a vida aperta.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'improvised_care:rank1' },
                effects = { mitigation = 0.015, healing = 0.01 },
                x = 58,
                y = 62,
            },
            camp_routine = {
                label = 'Rotina de abrigo',
                description = 'Melhora recuperacao e preparo durante rotas de sobrevivencia.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'improvised_care:rank1' },
                effects = { healing = 0.02, staminaDrain = -0.01 },
                x = 58,
                y = 78,
            },
            wasteland_focus = {
                label = 'Foco da wasteland',
                description = 'Treinamento avancado para manter performance sob pressao.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'weathered_lungs:rank2', 'blood_calm:rank2' },
                effects = { damage = 0.02, mitigation = 0.02 },
                x = 82,
                y = 46,
            },
            hard_route = {
                label = 'Rota dificil',
                description = 'Especializacao final para travessias perigosas.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'wasteland_focus:rank1', 'camp_routine:rank2' },
                effects = { mitigation = 0.025, staminaDrain = -0.025 },
                x = 94,
                y = 62,
            },
        },
    },
    ['class.warrior'] = {
        label = 'Guerreiro',
        description = 'Ramo de linha de frente com mitigacao, controle e presenca.',
        category = 'Classe',
        class = 'warrior',
        nodes = {
            shield_memory = {
                label = 'Memoria de escudo',
                description = 'Postura mais estavel ao absorver dano.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { mitigation = 0.02 },
                x = 10,
                y = 46,
            },
            breaker = {
                label = 'Quebra-linha',
                description = 'Aumenta dano em janelas curtas de combate pesado.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'shield_memory:rank2' },
                effects = { damage = 0.025 },
                x = 42,
                y = 28,
            },
            iron_breath = {
                label = 'Fole de ferro',
                description = 'Reduz perda de fole ao segurar posicao em combate.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'shield_memory:rank1' },
                effects = { staminaDrain = -0.02 },
                x = 38,
                y = 64,
            },
            counterweight = {
                label = 'Contrapeso',
                description = 'Transforma defesa em abertura para contra-ataque.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'breaker:rank1' },
                effects = { damage = 0.02, mitigation = 0.01 },
                x = 62,
                y = 20,
            },
            hold_the_line = {
                label = 'Segurar linha',
                description = 'Aprimora mitigacao quando o guerreiro esta sob pressao.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'iron_breath:rank2' },
                effects = { mitigation = 0.025 },
                x = 62,
                y = 70,
            },
            guard_stance_rank = {
                label = 'Postura defensiva II',
                description = 'Desbloqueia rank adicional da habilidade de guerreiro.',
                type = 'active',
                ability = 'guard_stance',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'shield_memory:rank3', 'hold_the_line:rank1' },
                x = 82,
                y = 46,
            },
            last_bastion = {
                label = 'Ultimo bastiao',
                description = 'Especializacao final de defesa agressiva.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'guard_stance_rank:rank1', 'counterweight:rank2' },
                effects = { damage = 0.02, mitigation = 0.03 },
                x = 94,
                y = 34,
            },
        },
    },
    ['class.hunter'] = {
        label = 'Cacador',
        description = 'Ramo de precisao, rastreio e dano a distancia.',
        category = 'Classe',
        class = 'hunter',
        nodes = {
            clean_draw = {
                label = 'Saque limpo',
                description = 'Melhora precisao e preparo em emboscadas.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { accuracy = 0.02 },
                x = 10,
                y = 46,
            },
            trail_reader = {
                label = 'Leitor de trilhas',
                description = 'Aprimora rastreio e leitura de terreno.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'clean_draw:rank2' },
                effects = { tracking = 0.035 },
                x = 42,
                y = 66,
            },
            breath_control = {
                label = 'Controle de folego',
                description = 'Reduz desgaste ao mirar, correr e reposicionar.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'clean_draw:rank1' },
                effects = { staminaDrain = -0.02, accuracy = 0.01 },
                x = 40,
                y = 28,
            },
            weak_spot = {
                label = 'Ponto fraco',
                description = 'Melhora dano quando o alvo ja foi lido.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'breath_control:rank2' },
                effects = { damage = 0.025 },
                x = 62,
                y = 24,
            },
            silent_route = {
                label = 'Rota silenciosa',
                description = 'Aumenta rastreio e precisao em aproximacoes longas.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'trail_reader:rank1' },
                effects = { tracking = 0.025, accuracy = 0.015 },
                x = 62,
                y = 72,
            },
            mark_prey_rank = {
                label = 'Marcar presa II',
                description = 'Desbloqueia rank adicional da habilidade de cacador.',
                type = 'active',
                ability = 'mark_prey',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'clean_draw:rank3', 'weak_spot:rank1' },
                x = 82,
                y = 46,
            },
            perfect_angle = {
                label = 'Angulo perfeito',
                description = 'Especializacao final para disparos decisivos.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'mark_prey_rank:rank1', 'silent_route:rank2' },
                effects = { accuracy = 0.03, damage = 0.02 },
                x = 94,
                y = 60,
            },
        },
    },
    ['class.medic'] = {
        label = 'Medico',
        description = 'Ramo de cura, triagem e estabilizacao.',
        category = 'Classe',
        class = 'medic',
        nodes = {
            steady_hands = {
                label = 'Maos firmes',
                description = 'Aumenta consistencia em suporte medico.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { healing = 0.025 },
                x = 10,
                y = 46,
            },
            trauma_drill = {
                label = 'Protocolo de trauma',
                description = 'Reduz falhas em recuperacoes sob pressao.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'steady_hands:rank2' },
                effects = { mitigation = 0.01, healing = 0.025 },
                x = 42,
                y = 28,
            },
            clean_pressure = {
                label = 'Pressao limpa',
                description = 'Aprimora estabilizacao rapida em ferimentos severos.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'steady_hands:rank1' },
                effects = { healing = 0.02 },
                x = 40,
                y = 66,
            },
            field_anatomy = {
                label = 'Anatomia de campo',
                description = 'Melhora cura e leitura de risco durante suporte.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'trauma_drill:rank1' },
                effects = { healing = 0.025, mitigation = 0.005 },
                x = 62,
                y = 20,
            },
            steady_pulse = {
                label = 'Pulso estavel',
                description = 'Mantem eficiencia em atendimento prolongado.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'clean_pressure:rank2' },
                effects = { staminaDrain = -0.015, healing = 0.015 },
                x = 62,
                y = 72,
            },
            field_triage_rank = {
                label = 'Triagem de campo II',
                description = 'Desbloqueia rank adicional da habilidade de medico.',
                type = 'active',
                ability = 'field_triage',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'steady_hands:rank3', 'field_anatomy:rank1' },
                x = 82,
                y = 46,
            },
            second_wind = {
                label = 'Segundo folego',
                description = 'Especializacao final para sustentar a equipe em crise.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'field_triage_rank:rank1', 'steady_pulse:rank2' },
                effects = { healing = 0.035, mitigation = 0.015 },
                x = 94,
                y = 62,
            },
        },
    },
    ['class.survivor'] = {
        label = 'Sobrevivente',
        description = 'Ramo de resistencia, utilidade e autonomia.',
        category = 'Classe',
        class = 'survivor',
        nodes = {
            ration_mind = {
                label = 'Mente racionada',
                description = 'Poupa energia em travessias longas.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { staminaDrain = -0.025 },
                x = 10,
                y = 46,
            },
            patched_nerves = {
                label = 'Nervos remendados',
                description = 'Mantem estabilidade quando a situacao degrada.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'ration_mind:rank2' },
                effects = { mitigation = 0.015 },
                x = 42,
                y = 66,
            },
            dry_pack = {
                label = 'Mochila seca',
                description = 'Melhora preparo e manutencao de suprimentos.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'ration_mind:rank1' },
                effects = { crafting = 0.015, staminaDrain = -0.01 },
                x = 40,
                y = 28,
            },
            grit_teeth = {
                label = 'Dentes cerrados',
                description = 'Aumenta resistencia quando tudo fica ruim.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'patched_nerves:rank1' },
                effects = { mitigation = 0.025 },
                x = 62,
                y = 72,
            },
            old_paths = {
                label = 'Caminhos antigos',
                description = 'Aprimora rotas seguras e leitura de territorio.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'dry_pack:rank2' },
                effects = { tracking = 0.025, staminaDrain = -0.015 },
                x = 62,
                y = 22,
            },
            grit_rank = {
                label = 'Tenacidade II',
                description = 'Desbloqueia rank adicional da habilidade de sobrevivente.',
                type = 'active',
                ability = 'grit',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'ration_mind:rank3', 'grit_teeth:rank1' },
                x = 82,
                y = 46,
            },
            never_lost = {
                label = 'Nunca perdido',
                description = 'Especializacao final de autonomia extrema.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'grit_rank:rank1', 'old_paths:rank2' },
                effects = { tracking = 0.03, mitigation = 0.02 },
                x = 94,
                y = 30,
            },
        },
    },
    ['class.engineer'] = {
        label = 'Engenheiro',
        description = 'Ramo tecnico com craft, improviso e suporte de equipamento.',
        category = 'Classe',
        class = 'engineer',
        nodes = {
            bench_eye = {
                label = 'Olho de bancada',
                description = 'Melhora leitura de pecas e ajustes de campo.',
                type = 'passive',
                maxRank = 3,
                costPerRank = { 1, 1, 2 },
                effects = { crafting = 0.025 },
                x = 10,
                y = 46,
            },
            spare_parts = {
                label = 'Pecas sobressalentes',
                description = 'Aumenta eficiencia em improvisos tecnicos.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'bench_eye:rank2' },
                effects = { crafting = 0.035 },
                x = 42,
                y = 28,
            },
            field_caliper = {
                label = 'Calibre de campo',
                description = 'Melhora ajustes rapidos em equipamentos instaveis.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 2 },
                requires = { 'bench_eye:rank1' },
                effects = { accuracy = 0.01, crafting = 0.02 },
                x = 40,
                y = 66,
            },
            reinforced_fix = {
                label = 'Reparo reforcado',
                description = 'Aumenta confiabilidade de reparos sob pressao.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'spare_parts:rank1' },
                effects = { crafting = 0.025, mitigation = 0.005 },
                x = 62,
                y = 22,
            },
            quick_rig = {
                label = 'Montagem rapida',
                description = 'Reduz desgaste e melhora utilidade tecnica em campo.',
                type = 'passive',
                maxRank = 2,
                costPerRank = { 2, 3 },
                requires = { 'field_caliper:rank2' },
                effects = { staminaDrain = -0.015, crafting = 0.02 },
                x = 62,
                y = 72,
            },
            field_rig_rank = {
                label = 'Improviso tecnico II',
                description = 'Desbloqueia rank adicional da habilidade de engenheiro.',
                type = 'active',
                ability = 'field_rig',
                maxRank = 1,
                costPerRank = { 3 },
                requires = { 'bench_eye:rank3', 'reinforced_fix:rank1' },
                x = 82,
                y = 46,
            },
            master_patch = {
                label = 'Remendo mestre',
                description = 'Especializacao final em improviso tecnico.',
                type = 'passive',
                maxRank = 1,
                costPerRank = { 4 },
                requires = { 'field_rig_rank:rank1', 'quick_rig:rank2' },
                effects = { crafting = 0.04, mitigation = 0.01 },
                x = 94,
                y = 62,
            },
        },
    },
}
